name: compile

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install cowsay
        run: |
          sudo apt-get -y install cowsay
      - name: Create readme
        run: |
          echo "$(echo $'```\r\n')$(cowsay -r "don't be a stranger")$(echo $'\r\n```')" > README.md
      - name: Commit readme
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add: "./README.md"
