name: Daily Workflow with Cowsay and Sine Curve Commits

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install cowsay
        run: npm i -g cowsay
      
      - name: Create README with cowsay
        run: |
          echo "$(echo $'```\r\n')$(cowsay -r "hello?")$(echo $'\r\n```')" > README.md
      
      - name: Commit README updates
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add: "./README.md"
      
      - name: Checkout repository again for sine commits
        uses: actions/checkout@v3

      - name: Generate Sine Curve Commits
        run: |
          FILE="sine.txt"
          if [ ! -f "$FILE" ]; then
            echo "Sine Commit Log" > "$FILE"
          fi

          # Maximum commits at the peak of the sine curve.
          max_commits=10

          # Loop over 7 days where day 0 is 6 days ago and day 6 is today.
          for day in {0..6}; do
              # Calculate commit count using a sine function.
              commits=$(python3 -c "import math; print(int(round(math.sin(((($day + 1)/8.0)*math.pi))*$max_commits)))")
              
              # Compute the commit date.
              commit_date=$(date -d "$((6 - day)) days ago" +"%Y-%m-%dT12:00:00")
              
              echo "For date $commit_date, making $commits commit(s)"
              
              if [ $commits -gt 0 ]; then
                for ((i=1; i<=commits; i++)); do
                  echo "Sine commit for $commit_date – commit #$i" >> "$FILE"
                  git add "$FILE"
                  # Backdate the commit.
                  GIT_AUTHOR_DATE="$commit_date" GIT_COMMITTER_DATE="$commit_date" git commit -m "Sine commit for $commit_date – commit #$i"
                done
              fi
          done

          # Pull the latest changes to avoid non-fast-forward issues, then push the sine commits.
          git pull --rebase origin master
          git push origin master
